site_name: IHC - Grupo 03
site_description: "Repositório do grupo 03 de IHC"
repo_name: '2024.2-Grupo03'
repo_url: 'https://github.com/Interacao-Humano-Computador/2024.2-Grupo03'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - contention.code.copy
  language: pt-BR
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Modo escuro
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Modo claro
      primary: teal
      accent: lime
