site_name: IHC - Neoenergia
site_description: "Repositório do grupo 03 de IHC"
repo_name: '2024.2-Neoenergia'
repo_url: 'https://github.com/Interacao-Humano-Computador/2024.2-Neoenergia'

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde
  - admonition

plugins:
  - glightbox

nav:
  - Início: index.md
  
  - Apresentações:
    - Apresentação 01: apresentações/apresentacao01.md
    - Apresentação 02: apresentações/apresentacao02.md
    - Apresentação 03: apresentações/apresentacao03.md
  
  - Atas: 
    - Ata 01: atas/ata01.md
    - Ata 02: atas/ata02.md
  
  - Planejamento: 
    - Cronograma: planejamento/cronograma.md
    - Ferramentas: planejamento/ferramentas.md
    - Heatmap: planejamento/heatmap.md
    - Sites Avaliados: planejamento/sites-avaliados.md
    - Site Escolhido: planejamento/site-escolhido.md
    - Processo de Design: planejamento/processo-design.md

  - Análise de Requisitos:
    - Aspectos Éticos: analise-requisitos/aspectos-eticos.md
    - Perfil de Usuário: analise-requisitos/perfil-usuario.md
    - Cenários: analise-requisitos/cenarios.md
    - Personas: analise-requisitos/personas.md
    - Análise de Tarefas:
      - GOMS: analise-requisitos/goms.md
    - Metas de Usabilidade: analise-requisitos/metas-usabilidade.md
    - Príncipios Gerais: analise-requisitos/principios-gerais.md
    - Guia de Estilo: analise-requisitos/guia-estilo.md
    - Características Gerais: analise-requisitos/caracteristicas-gerais.md

  - Verificação:
    - Nosso grupo:
      - Verificação 01: verificação/nosso-grupo/verificacao01.md
      - Verificação 02: verificação/nosso-grupo/verificacao02.md
      - Verificação 03: verificação/nosso-grupo/verificacao03.md
    - Grupo 04:
      - Verificação 01: verificação/grupo4/verificacao01.md
      - Verificação 02: verificação/grupo4/verificacao02.md
      - Verificação 03: verificação/grupo4/verificacao03.md

theme:
  icon:
    admonition:
      note: octicons/info-16
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - contention.code.copy
  language: pt-BR
  favicon: assets/neoenergia.png
  logo: assets/neoenergia.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Modo escuro
      primary: green
      accent: light blue
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Modo claro
      primary: green
      accent: amber

extra:
  version:
    provider: mike

extra_css: [stylesheets/extra.css]
  