site_name: IHC - Grupo 03
site_description: "Repositório do grupo 03 de IHC"
repo_name: '2024.2-Grupo03'
repo_url: 'https://github.com/Interacao-Humano-Computador/2024.2-Grupo03'

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - glightbox

nav:
  - Início: index.md
  
  - Apresentações:
    - Apresentação 01: apresentações/apresentacao01.md
  
  - Atas: 
    - Ata 01: atas/ata01.md
  
  - Planejamento: 
    - Cronograma: planejamento/cronograma.md
    - Ferramentas: planejamento/ferramentas.md
    - Heatmap: planejamento/heatmap.md
    - Sites Avaliados: planejamento/sites-avaliados.md
    - Site Escolhido: planejamento/site-escolhido.md
    - Processo de Design: planejamento/processo-design.md

  - Verificação:
    - Nosso grupo:
      - Verificação 01: verificação/verificacao-nosso-grupo.md
    - Grupo 04:
      - Verificação 01: verificação/verificacao-grupo4.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - contention.code.copy
  language: pt-BR
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Modo escuro
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Modo claro
      primary: teal
      accent: lime
